### PR TITLE
Merge pull request #1 from devopscube/feature

### PR DESCRIPTION
**Pull request by kkapadia4**
Update README.md

### CODE REVIEW

**Comment by SahityaBattula** [comment]
closed

**Comment by kishan1988-hub** [comment]
made update

**Comment by mokadir** [comment]
Testing multibranch

**Comment by chandrababu-ve** [comment]
code

**Comment by Sijibomi-stack** [comment]
Testing mainbranch

**Comment by iam-vigneshv** [comment]
new commit

**Pull request closed without merging**
